services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run --config /config/adguardhome-sync.yaml
    volumes:
      - /home/mcrummett/adguardhome_sync/adguardhome-sync.yaml:/config/adguardhome-sync.yaml
    ports:
      - 8082:8082
    restart: unless-stopped
